-include ../Makefile

create: ## run create
	$(call gcc,$(CURRENT_DIR)/create.c)
	$(call exec)

exit: ## run exit
	$(call gcc,$(CURRENT_DIR)/exit.c)
	$(call exec)

exit2: ## run exit2
	$(call gcc,$(CURRENT_DIR)/exit2.c)
	$(call exec)

cleanup: ## run cleanup
	$(call gcc,$(CURRENT_DIR)/cleanup.c)
	$(call exec)

timedlock: ## run timedlock
	$(call gcc,$(CURRENT_DIR)/timedlock.c)
	$(call exec)

barrier: ## run barrier
	$(call gcc,$(CURRENT_DIR)/barrier.c)
	$(call exec)
