-include ../Makefile

create: ## run create
	$(call gcc,$(CURRENT_DIR)/create.c)
	$(call exec)

exit: ## run exit
	$(call gcc,$(CURRENT_DIR)/exit.c)
	$(call exec)

exit2: ## run exit2
	$(call gcc,$(CURRENT_DIR)/exit2.c)
	$(call exec)
