-include ../Makefile

ls: ## run ls
	$(call gcc,$(CURRENT_DIR)/ls.c)
	$(call exec,/dev)

io: ## run io
	$(call gcc,$(CURRENT_DIR)/io.c)
	$(call exec)

stdio: ## run stdio
	$(call gcc,$(CURRENT_DIR)/stdio.c)
	$(call exec)

process: ## run process
	$(call gcc,$(CURRENT_DIR)/process.c)
	$(call exec)

shell: ## run shell
	$(call gcc,$(CURRENT_DIR)/shell.c)
	$(call exec)

error: ## run error
	$(call gcc,$(CURRENT_DIR)/error.c)
	$(call exec)

uid: ## run uid
	$(call gcc,$(CURRENT_DIR)/uid.c)
	$(call exec)

signal: ## run signal
	$(call gcc,$(CURRENT_DIR)/signal.c)
	$(call exec)
