-include ../Makefile

pipe: ## run pipe
	$(call gcc,$(CURRENT_DIR)/pipe.c)
	make run

pager: ## run pager
	$(call gcc,$(CURRENT_DIR)/pager.c)
	make run

popen: ## run popen
	$(call gcc,$(CURRENT_DIR)/popen.c)
	make run
