-include ../Makefile

sigusr: ## run sigusr
	$(call gcc,$(CURRENT_DIR)/sigusr.c)
	make run

getpwnam: ## run getpwnam
	$(call gcc,$(CURRENT_DIR)/getpwnam.c)
	make run

sigpending: ## run sigpending
	$(call gcc,$(CURRENT_DIR)/sigpending.c)
	make run

sigsetjmp: ## run sigsetjmp
	$(call gcc,$(CURRENT_DIR)/sigsetjmp.c)
	make run
