-include ../Makefile

sigusr: ## run sigusr
	$(call gcc,$(CURRENT_DIR)/sigusr.c)
	make run

getpwnam: ## run getpwnam
	$(call gcc,$(CURRENT_DIR)/getpwnam.c)
	make run

sigpending: ## run sigpending
	$(call gcc,$(CURRENT_DIR)/sigpending.c)
	make run

sigsetjmp: ## run sigsetjmp
	$(call gcc,$(CURRENT_DIR)/sigsetjmp.c)
	make run

sigsuspend: ## run sigsuspend
	$(call gcc,$(CURRENT_DIR)/sigsuspend.c)
	make run

atomic: ## run atomic
	$(call gcc,$(CURRENT_DIR)/atomic.c)
	make run

system: ## run system
	$(call gcc,$(CURRENT_DIR)/system.c)
	make run

job: ## run job
	$(call gcc,$(CURRENT_DIR)/job.c)
	make run
