-include ../Makefile

fgetc: ## run fgetc
	$(call gcc,$(CURRENT_DIR)/fgetc.c)
	$(call exec)

fgets: ## run fgets
	$(call gcc,$(CURRENT_DIR)/fgets.c)
	$(call exec)

tmpfile: ## run tmpfile
	$(call gcc,$(CURRENT_DIR)/tmpfile.c)
	$(call exec)

mkstemp: ## run mkstemp
	$(call gcc,$(CURRENT_DIR)/mkstemp.c)
	$(call exec)
